name: flutter_installer
description: Flutter Installer.

version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_chooser:
    path: ./plugin/file_chooser
  bitsdojo_window: ^0.1.0+1
  cupertino_icons: ^1.0.2
  filepicker_windows: ^2.0.0
  flutter_svg: ^0.21.0+1
  intl: ^0.17.0
  lottie: ^1.0.1
  pedantic: ^1.11.0
  process_run: ^0.12.1
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  file_selector: ^0.8.2
  file_selector_linux: ^0.0.2
  file_selector_macos: ^0.0.4
  file_selector_windows: ^0.0.2
  http: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/status_icons/
    - assets/icons/flutter_icons/
    - assets/ides/
    - assets/fonts/
    - assets/fonts/Inter/
    - assets/fonts/IconsFont/
    - assets/fonts/LexendDeca/
    - assets/lottie/
    - assets/scripts/path/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Bold.ttf
    - family: IconsFont
      fonts:
        - asset: assets/fonts/IconsFont/icons.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca/LexendDeca.ttf
