name: fluttermatic
description: FlutterMatic helps in managing your system's Flutter setup environment and makes development with Flutter easier.
publish_to: none
version: 0.0.1-alpha

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependencies
  bitsdojo_window: ^0.1.1+1
  connectivity_plus: ^2.2.1
  pubspec_parse: ^1.2.0
  file_selector: ^0.8.3
  file_selector_linux: ^0.0.2+1
  file_selector_macos: ^0.0.4+1
  file_selector_windows: ^0.8.2
  flutter_markdown: ^0.6.9
  flutter_svg: ^1.0.3
  highlight: ^0.7.0
  http: ^0.13.4
  intl: ^0.17.0
  path_provider: ^2.0.9
  process_run: ^0.12.3+2
  provider: ^6.0.2
  retry: ^3.1.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  pub_api_client: ^2.2.1
  universal_disk_space: ^0.2.3

  # Package Info
  package_info_plus: ^1.4.0
  package_info_plus_linux: ^1.0.3
  package_info_plus_macos: ^1.3.0
  package_info_plus_windows: ^1.0.4

msix_config:
  display_name: FlutterMatic
  publisher_display_name: FlutterMatic
  msix_version: 0.0.0.1
  # certificate_path: ./CERTIFICATE.pfx
  identity_name: com.fluttermatic.manager
  publisher: CN=FLUTTERMATIC, O=FlutterMatic
  icons_background_color: transparent
  architecture: x64
  capabilities: "internetClient"
  # We want to be able to release this app on the Windows Store
  store: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Build Dependencies
  build_runner: ^2.1.7
  msix: ^3.2.0

  # Lint
  flutter_lints: ^1.0.4
  import_sorter: ^4.6.0

# Emoji Sorter Service
import_sorter:
  emojis: true

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/logos/
    - assets/images/icons/
    - assets/documentation/
    - CHANGELOG.md

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans/NotoSans-Bold.ttf