name: manager
description: Flutter App Manager
publish_to: none
version: 2.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  archive: ^3.1.2
  args: ^2.2.0
  async: ^2.6.1
  bitsdojo_window: ^0.1.1+1
  connectivity_plus: ^1.0.6
  file_selector: ^0.8.2
  file_selector_linux: ^0.0.2
  file_selector_macos: ^0.0.4
  file_selector_windows: ^0.0.2
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.6
  flutter_svg: ^0.22.0
  highlight: ^0.7.0
  http: ^0.13.3
  intl: ^0.17.0
  lottie: ^1.1.0
  package_info_plus: ^1.0.6
  package_info_plus_linux: ^1.0.3
  package_info_plus_macos: ^1.1.1
  package_info_plus_windows: ^1.0.3
  path_provider: ^2.0.2
  process_run: ^0.12.1+1
  provider: ^5.0.0
  retry: ^3.1.0
  shared_preferences: ^2.0.6
  unix_disk_space:
    git:
      url: https://github.com/yahu1031/unix_disk_space.git
  url_launcher: ^6.0.9

msix_config:
  display_name: Flutter Manager
  publisher_display_name: Fluttermatic
  msix_version: 0.0.1
  certificate_path: ./CERTIFICATE.pfx
  certificate_password: fluttermatic
  identity_name: fluttermanager
  publisher: CN=FLUTTERMATIC, O=Fluttermatic
  icons_background_color: transparent
  architecture: x64
  vs_generated_images_folder_path: ./assets/images
  start_menu_icon_path: ./assets/images/flutter_manager.png
  tile_icon_path: ./assets/images/flutter_manager.png
  capabilities: 'internetClient'

dev_dependencies:
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  msix: ^2.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/font/
    - assets/images/logos/
    - assets/images/icons/
    - assets/lottie/
    - assets/markdown/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/font/NotoSans-Regular.ttf
        - asset: assets/font/NotoSans-Bold.ttf
