name: manager
description: Flutter manager helps managing your system's Flutter setup environment and makes development with Flutter even easier.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependencies
  archive: ^3.1.2
  args: ^2.3.0
  async: ^2.8.1
  bitsdojo_window: ^0.1.1+1
  connectivity_plus: ^1.1.0
  file_selector: ^0.8.2
  file_selector_linux: ^0.0.2
  file_selector_macos: ^0.0.4
  file_selector_windows: ^0.0.2
  flutter_markdown: ^0.6.6
  flutter_svg: ^0.22.0
  highlight: ^0.7.0
  http: ^0.13.3
  intl: ^0.17.0
  lottie: ^1.2.1
  path_provider: ^2.0.5
  process_run: ^0.12.2+1
  provider: ^6.0.1
  retry: ^3.1.0
  shared_preferences: ^2.0.8
  url_launcher: ^6.0.12
  pub_api_client: ^2.1.1

  # Package Info
  package_info_plus: ^1.0.6
  package_info_plus_linux: ^1.0.3
  package_info_plus_macos: ^1.1.1
  package_info_plus_windows: ^1.0.3

  # Git Dependencies
  unix_disk_space:
    git:
      url: https://github.com/yahu1031/unix_disk_space.git

msix_config:
  display_name: Flutter Manager
  publisher_display_name: Fluttermatic
  msix_version: 0.0.0.2
  certificate_path: ./CERTIFICATE.pfx
  certificate_password: fluttermatic
  identity_name: fluttermanager
  publisher: CN=FLUTTERMATIC, O=Fluttermatic
  icons_background_color: transparent
  architecture: x64
  vs_generated_images_folder_path: ./assets/images/app_icons/
  capabilities: "internetClient"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Build Dependencies
  build_runner: ^2.0.5
  msix: ^2.1.3

  # Lint
  flutter_lints: ^1.0.4
  import_sorter: ^4.6.0

# Emoji Sorter Service
import_sorter:
  emojis: true

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/app_icons/
    - assets/images/logos/
    - assets/images/icons/
    - assets/images/placeholders/
    - assets/markdown/
    - assets/lottie/
    - changelog.md

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans/NotoSans-Bold.ttf
    - family: VictorMono
      fonts:
        - asset: assets/fonts/VictorMono/VictorMono-SemiBold.ttf
        - asset: assets/fonts/VictorMono/VictorMono-SemiBoldItalic.ttf
          style: italic
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca/LexendDeca-Bold.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-SemiBold.ttf
        - asset: assets/fonts/LexendDeca/LexendDeca-Medium.ttf
