name: flutter_installer
description: A new Flutter project.

version: 0.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bitsdojo_window: ^0.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  lottie: ^1.0.1
  pedantic: ^1.11.0
  process_run: ^0.12.1
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/fonts/Inter/
    - assets/fonts/IconsFont/
    - assets/fonts/LexendDeca/
    - assets/lottie/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Bold.ttf
    - family: IconsFont
      fonts:
        - asset: assets/fonts/IconsFont/icons.ttf
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca/LexendDeca.ttf
