name: fluttermatic
description: FlutterMatic helps in managing your system's Flutter setup environment and makes development with Flutter easier.
publish_to: none
version: 0.0.1-alpha

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependencies
  connectivity_plus: ^6.0.5
  flutter_riverpod: ^2.5.3
  pubspec_parse: ^1.3.0
  file_selector: ^1.0.3
  file_selector_linux: ^0.9.3
  file_selector_macos: ^0.9.4+2
  file_selector_windows: ^0.9.3+3
  flutter_markdown: ^0.7.4
  flutter_svg: ^2.0.10+1
  highlight: ^0.7.0
  http: ^1.2.2
  intl: ^0.19.0
  path_provider: ^2.1.4
  process_run: ^0.12.3+2
  retry: ^3.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  universal_disk_space: ^0.2.3

  pub_api_client:
    git:
      url: https://github.com/fluttertools/pub_api_client.git
      branch: main

  # Package Info
  package_info_plus: ^8.0.3

# msix_config:
#   display_name: FlutterMatic
#   publisher_display_name: FlutterMatic
#   msix_version: 0.0.0.1
#   # certificate_path: ./CERTIFICATE.pfx
#   identity_name: com.fluttermatic.manager
#   publisher: CN=FLUTTERMATIC, O=FlutterMatic
#   icons_background_color: transparent
#   architecture: x64
#   capabilities: "internetClient"
#   # We want to be able to release this app on the Windows Store
#   store: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Build Dependencies
  build_runner: ^2.3.3
  # msix: ^3.6.3

  # Lint
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0

# Emoji Sorter Service
import_sorter:
  emojis: true

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/logos/
    - assets/images/icons/
    - assets/documentation/
    - CHANGELOG.md

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans/NotoSans-Bold.ttf