name: manager
description: Flutter App Manager

publish_to: "none"

version: 0.0.1-alpha.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.1+1
  connectivity_plus: ^1.0.6
  cupertino_icons: ^1.0.3
  file_selector: ^0.8.2
  file_selector_linux: ^0.0.2
  file_selector_macos: ^0.0.4
  file_selector_windows: ^0.0.2
  http: ^0.13.3
  intl: ^0.17.0
  lottie: ^1.1.0
  path_provider: ^2.0.2
  process_run: ^0.12.1+1
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  pedantic: ^1.11.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/lottie/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          # - asset: assets/fonts/Inter/Inter-Bold.ttf
          # weight: 700
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca/LexendDeca.ttf
