name: script
description: FlutterMatic dev script(s). Generally used to build app.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  process_run: ^0.12.3+2
  ansicolor: ^2.0.1
  flutter_lints: ^1.0.4
  import_sorter: ^4.6.0