name: Analyzing Code

on:
  push:
    branches: [ redesign ]
jobs:
  flutter_analyze:
    name: Ananlyzing code on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '2.2.3'
          channel: 'stable'
      - name: Installing dependencies
        run: flutter pub get
      - name: Analyzing application code
        run: flutter analyze