name: Analyzing Code

on:
  push:
    branches: [ main ]

jobs:
  plugin_analyze:
    name: Ananlyzing code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: stable
      - name: Changing the directory
        run: cd plugin/file_chooser
      - name: Installing dependencies
        run: flutter pub get
      - name: Analyzing application code
        run: flutter analyze

  flutter_analyze:
    name: Ananlyzing code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: stable
      - name: Installing dependencies
        run: flutter pub get
      - name: Analyzing application code
        run: flutter analyze
