name: fm_installer
description: The FlutterMatic installer that helps install a new version of FlutterMatic.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  process_run: ^0.12.3+2

dev_dependencies:
  flutter_lints: ^1.0.4
  import_sorter: ^4.6.0